/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProofRegistry } from "./ProofRegistry";
export type { ProofRegistryV2 } from "./ProofRegistryV2";
export * as factories from "./factories";
export { ProofRegistry__factory } from "./factories/ProofRegistry__factory";
export { ProofRegistryV2__factory } from "./factories/ProofRegistryV2__factory";
