/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProofRegistryV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "getByFileSha"
      | "getByMediaId"
      | "mediaIdByFileSha"
      | "register"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Registered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getByFileSha",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getByMediaId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mediaIdByFileSha",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike, BytesLike, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getByFileSha",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getByMediaId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mediaIdByFileSha",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
}

export namespace RegisteredEvent {
  export type InputTuple = [
    mediaId: BytesLike,
    ownerSha: BytesLike,
    fileSha256: BytesLike,
    ipfsCid: string,
    submitter: AddressLike,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [
    mediaId: string,
    ownerSha: string,
    fileSha256: string,
    ipfsCid: string,
    submitter: string,
    blockNumber: bigint
  ];
  export interface OutputObject {
    mediaId: string;
    ownerSha: string;
    fileSha256: string;
    ipfsCid: string;
    submitter: string;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofRegistryV2 extends BaseContract {
  connect(runner?: ContractRunner | null): ProofRegistryV2;
  waitForDeployment(): Promise<this>;

  interface: ProofRegistryV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getByFileSha: TypedContractMethod<
    [fileSha256: BytesLike],
    [[boolean, string] & { exists: boolean; mediaId: string }],
    "view"
  >;

  getByMediaId: TypedContractMethod<
    [mediaId: BytesLike],
    [
      [boolean, string, string, string, bigint, string] & {
        exists: boolean;
        ownerSha: string;
        fileSha256: string;
        ipfsCid: string;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;

  mediaIdByFileSha: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  register: TypedContractMethod<
    [
      mediaId: BytesLike,
      ownerSha: BytesLike,
      fileSha256: BytesLike,
      ipfsCid: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getByFileSha"
  ): TypedContractMethod<
    [fileSha256: BytesLike],
    [[boolean, string] & { exists: boolean; mediaId: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getByMediaId"
  ): TypedContractMethod<
    [mediaId: BytesLike],
    [
      [boolean, string, string, string, bigint, string] & {
        exists: boolean;
        ownerSha: string;
        fileSha256: string;
        ipfsCid: string;
        timestamp: bigint;
        submitter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mediaIdByFileSha"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      mediaId: BytesLike,
      ownerSha: BytesLike,
      fileSha256: BytesLike,
      ipfsCid: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Registered"
  ): TypedContractEvent<
    RegisteredEvent.InputTuple,
    RegisteredEvent.OutputTuple,
    RegisteredEvent.OutputObject
  >;

  filters: {
    "Registered(bytes32,bytes32,bytes32,string,address,uint256)": TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
    Registered: TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
  };
}
