/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProofRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getProof" | "registerProof"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProofRegistered"): EventFragment;

  encodeFunctionData(functionFragment: "getProof", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerProof",
    values: [BytesLike, BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProof",
    data: BytesLike
  ): Result;
}

export namespace ProofRegisteredEvent {
  export type InputTuple = [
    fileHash: BytesLike,
    emailSha: BytesLike,
    ipfsCid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fileHash: string,
    emailSha: string,
    ipfsCid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    fileHash: string;
    emailSha: string;
    ipfsCid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProofRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProofRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProof: TypedContractMethod<
    [fileHash: BytesLike],
    [
      [boolean, string, bigint, string] & {
        exists: boolean;
        ownerEmailSha: string;
        timestamp: bigint;
        ipfsCid: string;
      }
    ],
    "view"
  >;

  registerProof: TypedContractMethod<
    [fileHash: BytesLike, emailSha: BytesLike, ipfsCid: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [fileHash: BytesLike],
    [
      [boolean, string, bigint, string] & {
        exists: boolean;
        ownerEmailSha: string;
        timestamp: bigint;
        ipfsCid: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProof"
  ): TypedContractMethod<
    [fileHash: BytesLike, emailSha: BytesLike, ipfsCid: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProofRegistered"
  ): TypedContractEvent<
    ProofRegisteredEvent.InputTuple,
    ProofRegisteredEvent.OutputTuple,
    ProofRegisteredEvent.OutputObject
  >;

  filters: {
    "ProofRegistered(bytes32,bytes32,string,uint256)": TypedContractEvent<
      ProofRegisteredEvent.InputTuple,
      ProofRegisteredEvent.OutputTuple,
      ProofRegisteredEvent.OutputObject
    >;
    ProofRegistered: TypedContractEvent<
      ProofRegisteredEvent.InputTuple,
      ProofRegisteredEvent.OutputTuple,
      ProofRegisteredEvent.OutputObject
    >;
  };
}
