/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProofRegistry__factory } from "./ProofRegistry__factory";
export { ProofRegistryV2__factory } from "./ProofRegistryV2__factory";
